### PR TITLE
Retry applying patch up to 5 times and wait for operation to complete

### PR DESCRIPTION
**Pull request by cconstantin**

### CODE REVIEW

**Comment by fbaier-fn** [comment]
Rel to https://github.com/GoogleCloudPlatform/gke-autoneg-controller/issues/11 and https://github.com/GoogleCloudPlatform/gke-autoneg-controller/pull/12

As I mentioned in #11 I would have been also happy to contribute upstream and e.g. discuss if instead of linear we want maybe an exponential backoff, etc..

**Comment by realpha** [comment]
Would be really important to see this thing merged!

**Comment by mvanholsteijn** [comment]
AFAIK, retry has been implemented with #25

**Comment by soellman** [comment]
Closing, dupe of #25

**Pull request closed without merging**
