### PR TITLE
Add common app label

### PR DESCRIPTION
**Pull request by naseemkullah**

### CODE REVIEW

**Comment by naseemkullah** [comment]
bump

**Comment by morgante** [comment]
@soellman Can you PTAL (or add me as an admin on this repo)?

**Comment by naseemkullah** [comment]
> @soellman Can you PTAL (or add me as an admin on this repo)?

YES! @soellman, having @morgante help to admin this repo would be great!

**Comment by naseemkullah** [comment]
bump

**Comment by naseemkullah** [comment]
bump

**Comment by soellman** [comment]
Sorry this fell by the wayside! 

I like adding the `app:autoneg` label. The appended object types on resource names are part of the kubebuilder scaffolding - I'd prefer not to change them unless there's a compelling reason to override the kubebuilder default.

If we keep the additional `app` label and we don't keep the resource name changes, there would be just the modification to `kustomization.yaml`.

If you'd like to submit another commit, I'd be happy to merge. Sorry again this didn't get attention!

**Comment by naseemkullah** [comment]
what about the  removal of `namespace` from resources in favour of `namespace` being configured in `kusomtization.yaml` ?

**Comment by soellman** [comment]
What is your use case wanting to change the namespace name from `autoneg-system`? Are you trying to deploy autoneg to each namespace and if so, why?

**Comment by naseemkullah** [comment]
> What is your use case wanting to change the namespace name from `autoneg-system`? Are you trying to deploy autoneg to each namespace and if so, why?

What I mean is that since the namespace is specified in `kustomization.yaml`, putting them in the individual resource files is redundant.

**Comment by soellman** [comment]
Ah yes I understand, you're completely right that it's redundant!

The namespace specification is also part of the kubebuilder scaffolding, so if we're removing it only as part of a refactor, then I'd prefer not to make that change. It would keep those files simpler to accept a merge of new upstream changes from kubebuilder.

Unless there's some other aspect I'm not considering?

**Comment by naseemkullah** [comment]
> Ah yes I understand, you're completely right that it's redundant!
> 
> The namespace specification is also part of the kubebuilder scaffolding, so if we're removing it only as part of a refactor, then I'd prefer not to make that change. It would keep those files simpler to accept a merge of new upstream changes from kubebuilder.
> 
> Unless there's some other aspect I'm not considering?

Ah ok, I am unaware of these kubebuilder defaults. As such a PR should probably be made to kubebuilder itself to remove these redundancies. I'll fix this PR to only add `app` label

**Comment by soellman** [comment]
Sounds great, thanks!

**Comment by naseemkullah** [comment]
PTAL @soellman

**Review by soellman — APPROVED** [review]
Looks, good, thanks!

**Pull request merged**
